apiVersion: v2
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
description: A Helm chart for MOSIP mock-identity-system module
home: https://mosip.io
keywords:
- mosip
- mock-identity-system
maintainers:
- email: info@mosip.io
  name: MOSIP
name: mock-identity-system
type: application
version: 0.12.0
